### ISSUE TITLE
uni-pushy-admin TDOA参数

### ISSUE THREAD

**Issue by CaoTianxing** [SunSeekerX/upushy-server#6]
想问一下  store.state.config 中的TDOA是用来解决什么问题的，我看到页面第一次请求获取到了一个响应时间差，后面的所有请求时间戳都减去了这个TDOA

**Comment by SunSeekerX** [comment]
用来防止过期请求用的，客户端的时间可能不正确，这就导致api加密过不去。

**Comment by CaoTianxing** [comment]
ok  谢谢
